name: event_management_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  get: ^4.7.2
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  path: ^1.9.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0
  http: ^1.3.0
  flutter_stripe: ^11.4.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  dotted_border: ^2.1.0
  emoji_picker_flutter: ^4.3.0
  intl: ^0.19.0
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
