// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbPpWTUPMdr3Nn4d5l4INP02Dzu32Gz4g',
    appId: '1:208304211349:web:d88625a45a8fc5f196229c',
    messagingSenderId: '208304211349',
    projectId: 'event-management-app-e2100',
    authDomain: 'event-management-app-e2100.firebaseapp.com',
    storageBucket: 'event-management-app-e2100.firebasestorage.app',
    measurementId: 'G-ZLZ652QX03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDFci4NFQSk72al0HaOLtNv1tN5WwdqOs',
    appId: '1:208304211349:android:9d4d2b25e7a769de96229c',
    messagingSenderId: '208304211349',
    projectId: 'event-management-app-e2100',
    storageBucket: 'event-management-app-e2100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4fFW0XB6WCGFAzfrhTf4FkIvWZr8qZNU',
    appId: '1:208304211349:ios:d3af98e2ec9e93f396229c',
    messagingSenderId: '208304211349',
    projectId: 'event-management-app-e2100',
    storageBucket: 'event-management-app-e2100.firebasestorage.app',
    iosBundleId: 'com.ibrar.eventManagementApp',
  );
}
